// Generated by CoffeeScript 1.6.3
(function() {
  var el, insert;

  insert = require('insert-style');

  el = null;

  describe('Style', function() {
    return describe('#addRule()', function() {
      it('should set color to red after element is created', function() {
        el = $('<div class="test-element">text</div>').appendTo('body');
        insert('.test-element', 'color: rgb(255, 0, 0);');
        expect(el.css('color')).to.be.equal('rgb(255, 0, 0)');
        return el.remove();
      });
      return it('should set color to red before element is created', function() {
        insert('.test-element', 'color: rgb(255, 0, 0);');
        el = $('<div class="test-element">text</div>').appendTo('body');
        expect(el.css('color')).to.be.equal('rgb(255, 0, 0)');
        return el.remove();
      });
    });
  });

}).call(this);
