// Generated by CoffeeScript 1.6.3
(function() {
  var Style, style;

  Style = (function() {
    Style.prototype.sheet = null;

    function Style() {
      var style;
      style = document.createElement('style');
      style.appendChild(document.createTextNode(''));
      document.head.appendChild(style);
      this.sheet = style.sheet;
    }

    Style.prototype.addRule = function(selector, rule) {
      this.sheet.addRule(selector, rule);
      return this;
    };

    return Style;

  })();

  style = new Style;

  module.exports = function(selector, rule) {
    return style.addRule.call(style, selector, rule);
  };

}).call(this);
